export {default as Blog} from './Blog'
export {default as Feature} from './Feature'
export {default as Gallery} from './Gallery'
export {default as MainHeader} from './MainHeader'
export {default as Portfolio} from './Portfolio'
